version: "3"
services:
    www:
        build: .
        restart: unless-stopped
        ports: 
            - "8080:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
        networks:
            - default
        depends_on:
            - db
    db:
        image: mysql
        restart: unless-stopped
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: database
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: unless-stopped
        links: 
            - db:db
        ports:
            - 8888:80
volumes:
    persistent: